// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

//! Numeric parity tests for the `androidx.graphics.shapes` port in
//! `internal/core/graphics/shapes/`.
//!
//! `tests/shapes/golden/*.json` are generated by running the vendored Kotlin
//! sources (pinned androidx commit 23327507f7fc7d5b19d65fec4b090f60c970079b)
//! through `tests/shapes/src/GoldenGenerator.kt`; every f32 is stored as its
//! IEEE-754 bit pattern. See `tests/shapes/golden/README.md` for the tolerance
//! policy: values produced without transcendental functions or square roots
//! must be bit-exact; everything else must be within 1e-4 (the JVM and the
//! no_std/libm targets may round the last ulp differently).

use i_slint_core::graphics::shapes::{self, CornerRounding, Morph, Point, RoundedPolygon};
use std::collections::BTreeMap;

const CENTER: Point = Point { x: 0.5, y: 0.5 };

fn cr(radius: f32) -> CornerRounding {
    CornerRounding::new(radius, 0.)
}

fn crs(radius: f32, smoothing: f32) -> CornerRounding {
    CornerRounding::new(radius, smoothing)
}

/// Port of `Matrix().apply { rotateZ(deg) }.map(point)` from
/// androidx.compose.ui.graphics: `r = deg * (PI / 180)` is computed in f64 and
/// `sin`/`cos` are narrowed to f32, matching the Kotlin implementation.
fn rotate_z(degrees: f32) -> impl Fn(f32, f32) -> Point {
    let r = degrees as f64 * (std::f64::consts::PI / 180.);
    let s = r.sin() as f32;
    let c = r.cos() as f32;
    move |x, y| Point { x: c * x - s * y, y: s * x + c * y }
}

fn scale(sx: f32, sy: f32) -> impl Fn(f32, f32) -> Point {
    move |x, y| Point { x: sx * x, y: sy * y }
}

fn custom(
    points: &[(f32, f32)],
    roundings: &[CornerRounding],
    reps: usize,
    mirroring: bool,
) -> RoundedPolygon {
    shapes::custom_polygon(points, roundings, CENTER, reps, mirroring).unwrap()
}

fn star(
    num_vertices_per_radius: usize,
    radius: f32,
    inner_radius: f32,
    rounding: CornerRounding,
    inner_rounding: Option<CornerRounding>,
) -> RoundedPolygon {
    shapes::star(
        num_vertices_per_radius,
        radius,
        inner_radius,
        rounding,
        inner_rounding,
        None,
        Point::ZERO,
    )
    .unwrap()
}

/// The `MaterialShapes` object from
/// `androidx/compose/material3/MaterialShapes.kt`, ported member by member.
/// Every shape is `.normalized()` like the Kotlin getters.
mod material {
    use super::*;

    const CR15: CornerRounding = CornerRounding::new(0.15, 0.);
    const CR20: CornerRounding = CornerRounding::new(0.2, 0.);
    const CR30: CornerRounding = CornerRounding::new(0.3, 0.);
    const CR50: CornerRounding = CornerRounding::new(0.5, 0.);
    const CR100: CornerRounding = CornerRounding::new(1.0, 0.);

    fn n(p: RoundedPolygon) -> RoundedPolygon {
        p.normalized()
    }

    fn circle() -> RoundedPolygon {
        n(shapes::circle(10, 1., Point::ZERO).unwrap())
    }

    fn square() -> RoundedPolygon {
        n(shapes::rectangle(1., 1., CR30, None, Point::ZERO).unwrap())
    }

    fn slanted() -> RoundedPolygon {
        n(custom(
            &[(0.926, 0.970), (-0.021, 0.967)],
            &[crs(0.189, 0.811), crs(0.187, 0.057)],
            2,
            false,
        ))
    }

    fn arch() -> RoundedPolygon {
        n(RoundedPolygon::regular(
            4,
            1.,
            Point::ZERO,
            CornerRounding::UNROUNDED,
            Some(&[CR100, CR100, CR20, CR20]),
        )
        .unwrap()
        .transformed(&rotate_z(-135.)))
    }

    fn fan() -> RoundedPolygon {
        n(custom(
            &[(1.004, 1.000), (0.000, 1.000), (0.000, -0.003), (0.978, 0.020)],
            &[crs(0.148, 0.417), cr(0.151), cr(0.148), cr(0.803)],
            1,
            false,
        ))
    }

    fn arrow() -> RoundedPolygon {
        n(custom(
            &[(0.500, 0.892), (-0.216, 1.050), (0.499, -0.160), (1.225, 1.060)],
            &[cr(0.313), cr(0.207), crs(0.215, 1.0), cr(0.211)],
            1,
            false,
        ))
    }

    fn semi_circle() -> RoundedPolygon {
        n(shapes::rectangle(
            1.6,
            1.,
            CornerRounding::UNROUNDED,
            Some(vec![CR20, CR20, CR100, CR100]),
            Point::ZERO,
        )
        .unwrap())
    }

    fn oval() -> RoundedPolygon {
        n(shapes::circle(8, 1., Point::ZERO)
            .unwrap()
            .transformed(&scale(1., 0.64))
            .transformed(&rotate_z(-45.)))
    }

    fn pill() -> RoundedPolygon {
        n(custom(
            &[(0.961, 0.039), (1.001, 0.428), (1.000, 0.609)],
            &[cr(0.426), CornerRounding::UNROUNDED, cr(1.0)],
            2,
            true,
        ))
    }

    fn triangle() -> RoundedPolygon {
        n(RoundedPolygon::regular(3, 1., Point::ZERO, CR20, None)
            .unwrap()
            .transformed(&rotate_z(-90.)))
    }

    fn diamond() -> RoundedPolygon {
        n(custom(&[(0.500, 1.096), (0.040, 0.500)], &[crs(0.151, 0.524), cr(0.159)], 2, false))
    }

    fn clam_shell() -> RoundedPolygon {
        n(custom(
            &[(0.171, 0.841), (-0.020, 0.500), (0.170, 0.159)],
            &[cr(0.159), cr(0.140), cr(0.159)],
            2,
            false,
        ))
    }

    fn pentagon() -> RoundedPolygon {
        n(custom(
            &[(0.500, -0.009), (1.030, 0.365), (0.828, 0.970)],
            &[cr(0.172), cr(0.164), cr(0.169)],
            1,
            true,
        ))
    }

    fn gem() -> RoundedPolygon {
        n(custom(
            &[(0.499, 1.023), (-0.005, 0.792), (0.073, 0.258), (0.433, -0.000)],
            &[crs(0.241, 0.778), cr(0.208), cr(0.228), cr(0.491)],
            1,
            true,
        ))
    }

    fn sunny() -> RoundedPolygon {
        n(star(8, 1., 0.8, CR15, None))
    }

    fn very_sunny() -> RoundedPolygon {
        n(custom(&[(0.500, 1.080), (0.358, 0.843)], &[cr(0.085), cr(0.085)], 8, false))
    }

    fn cookie_4_sided() -> RoundedPolygon {
        n(custom(&[(1.237, 1.236), (0.500, 0.918)], &[cr(0.258), cr(0.233)], 4, false))
    }

    fn cookie_6_sided() -> RoundedPolygon {
        n(custom(&[(0.723, 0.884), (0.500, 1.099)], &[cr(0.394), cr(0.398)], 6, false))
    }

    fn cookie_7_sided() -> RoundedPolygon {
        n(star(7, 1., 0.75, CR50, None).transformed(&rotate_z(-90.)))
    }

    fn cookie_9_sided() -> RoundedPolygon {
        n(star(9, 1., 0.8, CR50, None).transformed(&rotate_z(-90.)))
    }

    fn cookie_12_sided() -> RoundedPolygon {
        n(star(12, 1., 0.8, CR50, None).transformed(&rotate_z(-90.)))
    }

    fn ghostish() -> RoundedPolygon {
        n(custom(
            &[(0.500, 0.0), (1.0, 0.0), (1.0, 1.140), (0.575, 0.906)],
            &[cr(1.0), cr(1.0), crs(0.254, 0.106), cr(0.253)],
            1,
            true,
        ))
    }

    fn clover_4_leaf() -> RoundedPolygon {
        n(custom(
            &[(0.500, 0.074), (0.725, -0.099)],
            &[CornerRounding::UNROUNDED, cr(0.476)],
            4,
            true,
        ))
    }

    fn clover_8_leaf() -> RoundedPolygon {
        n(custom(
            &[(0.500, 0.036), (0.758, -0.101)],
            &[CornerRounding::UNROUNDED, cr(0.209)],
            8,
            false,
        ))
    }

    fn burst() -> RoundedPolygon {
        n(custom(&[(0.500, -0.006), (0.592, 0.158)], &[cr(0.006), cr(0.006)], 12, false))
    }

    fn soft_burst() -> RoundedPolygon {
        n(custom(&[(0.193, 0.277), (0.176, 0.055)], &[cr(0.053), cr(0.053)], 10, false))
    }

    fn boom() -> RoundedPolygon {
        n(custom(&[(0.457, 0.296), (0.500, -0.051)], &[cr(0.007), cr(0.007)], 15, false))
    }

    fn soft_boom() -> RoundedPolygon {
        n(custom(
            &[(0.733, 0.454), (0.839, 0.437), (0.949, 0.449), (0.998, 0.478)],
            &[CornerRounding::UNROUNDED, cr(0.532), crs(0.439, 1.0), cr(0.174)],
            16,
            true,
        ))
    }

    fn flower() -> RoundedPolygon {
        n(custom(
            &[(0.370, 0.187), (0.416, 0.049), (0.479, 0.001)],
            &[CornerRounding::UNROUNDED, cr(0.381), cr(0.095)],
            8,
            true,
        ))
    }

    fn puffy() -> RoundedPolygon {
        n(custom(
            &[
                (0.500, 0.053),
                (0.545, -0.040),
                (0.670, -0.035),
                (0.717, 0.066),
                (0.722, 0.128),
                (0.777, 0.002),
                (0.914, 0.149),
                (0.926, 0.289),
                (0.881, 0.346),
                (0.940, 0.344),
                (1.003, 0.437),
            ],
            &[
                CornerRounding::UNROUNDED,
                cr(0.405),
                cr(0.426),
                cr(0.574),
                CornerRounding::UNROUNDED,
                cr(0.360),
                cr(0.660),
                cr(0.660),
                CornerRounding::UNROUNDED,
                cr(0.126),
                cr(0.255),
            ],
            2,
            true,
        )
        .transformed(&scale(1., 0.742)))
    }

    fn puffy_diamond() -> RoundedPolygon {
        n(custom(
            &[(0.870, 0.130), (0.818, 0.357), (1.000, 0.332)],
            &[cr(0.146), CornerRounding::UNROUNDED, cr(0.853)],
            4,
            true,
        ))
    }

    fn pixel_circle() -> RoundedPolygon {
        n(custom(
            &[
                (0.500, 0.000),
                (0.704, 0.000),
                (0.704, 0.065),
                (0.843, 0.065),
                (0.843, 0.148),
                (0.926, 0.148),
                (0.926, 0.296),
                (1.000, 0.296),
            ],
            &[CornerRounding::UNROUNDED; 8],
            2,
            true,
        ))
    }

    fn pixel_triangle() -> RoundedPolygon {
        n(custom(
            &[
                (0.110, 0.500),
                (0.113, 0.000),
                (0.287, 0.000),
                (0.287, 0.087),
                (0.421, 0.087),
                (0.421, 0.170),
                (0.560, 0.170),
                (0.560, 0.265),
                (0.674, 0.265),
                (0.675, 0.344),
                (0.789, 0.344),
                (0.789, 0.439),
                (0.888, 0.439),
            ],
            &[CornerRounding::UNROUNDED; 13],
            1,
            true,
        ))
    }

    fn bun() -> RoundedPolygon {
        n(custom(
            &[(0.796, 0.500), (0.853, 0.518), (0.992, 0.631), (0.968, 1.000)],
            &[CornerRounding::UNROUNDED, cr(1.), cr(1.), cr(1.)],
            2,
            true,
        ))
    }

    fn heart() -> RoundedPolygon {
        n(custom(
            &[(0.500, 0.268), (0.792, -0.066), (1.064, 0.276), (0.501, 0.946)],
            &[cr(0.016), cr(0.958), cr(1.0), cr(0.129)],
            1,
            true,
        ))
    }

    /// All `MaterialShapes` members, in the same order as `GoldenGenerator.kt`.
    pub fn all() -> Vec<(&'static str, RoundedPolygon)> {
        vec![
            ("circle", circle()),
            ("square", square()),
            ("slanted", slanted()),
            ("arch", arch()),
            ("fan", fan()),
            ("arrow", arrow()),
            ("semi_circle", semi_circle()),
            ("oval", oval()),
            ("pill", pill()),
            ("triangle", triangle()),
            ("diamond", diamond()),
            ("clam_shell", clam_shell()),
            ("pentagon", pentagon()),
            ("gem", gem()),
            ("sunny", sunny()),
            ("very_sunny", very_sunny()),
            ("cookie_4_sided", cookie_4_sided()),
            ("cookie_6_sided", cookie_6_sided()),
            ("cookie_7_sided", cookie_7_sided()),
            ("cookie_9_sided", cookie_9_sided()),
            ("cookie_12_sided", cookie_12_sided()),
            ("ghostish", ghostish()),
            ("clover_4_leaf", clover_4_leaf()),
            ("clover_8_leaf", clover_8_leaf()),
            ("burst", burst()),
            ("soft_burst", soft_burst()),
            ("boom", boom()),
            ("soft_boom", soft_boom()),
            ("flower", flower()),
            ("puffy", puffy()),
            ("puffy_diamond", puffy_diamond()),
            ("pixel_circle", pixel_circle()),
            ("pixel_triangle", pixel_triangle()),
            ("bun", bun()),
            ("heart", heart()),
        ]
    }
}

/// The primitive-constructor entries of `GoldenGenerator.kt` (non-MaterialShapes).
fn primitive_shapes() -> Vec<(&'static str, RoundedPolygon)> {
    vec![
        ("circle_default", shapes::circle(8, 1., Point::ZERO).unwrap()),
        ("circle_5", shapes::circle(5, 1., Point::ZERO).unwrap()),
        ("circle_3_smoothing", shapes::circle(3, 1.5, Point { x: 0.4, y: 0.6 }).unwrap()),
        (
            "rectangle_default",
            shapes::rectangle(2., 2., CornerRounding::UNROUNDED, None, Point::ZERO).unwrap(),
        ),
        (
            "rectangle_2x1_rounded",
            shapes::rectangle(2., 1., CornerRounding::new(0.15, 0.4), None, Point::ZERO).unwrap(),
        ),
        ("star_default", star(5, 1., 0.5, CornerRounding::UNROUNDED, None)),
        ("star_7", star(7, 2., 0.9, CornerRounding::new(0.1, 0.5), Some(cr(0.05)))),
        ("pill_2x1", shapes::pill(2., 1., 0., Point::ZERO).unwrap()),
        ("pill_1x3_smoothing", shapes::pill(1., 3., 0.8, Point::ZERO).unwrap()),
        (
            "pill_star_8",
            shapes::pill_star(
                2.,
                1.,
                8,
                0.5,
                CornerRounding::UNROUNDED,
                None,
                None,
                0.5,
                0.,
                Point::ZERO,
            )
            .unwrap(),
        ),
        (
            "pill_star_5_inner03",
            shapes::pill_star(
                1.,
                2.,
                5,
                0.3,
                CornerRounding::new(0.05, 0.7),
                None,
                None,
                0.8,
                0.25,
                Point::ZERO,
            )
            .unwrap(),
        ),
    ]
}

// --- golden comparison helpers ------------------------------------------------

fn f32_bits(v: &serde_json::Value) -> f32 {
    f32::from_bits(v.as_u64().unwrap() as u32)
}

fn load_golden(name: &str) -> serde_json::Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/shapes/golden/");
    serde_json::from_str(&std::fs::read_to_string(format!("{path}{name}")).unwrap()).unwrap()
}

struct Diff {
    mismatched_bits: usize,
    max_abs_diff: f32,
}

impl Diff {
    fn add(&mut self, expected: f32, actual: f32) {
        if expected.to_bits() != actual.to_bits() {
            self.mismatched_bits += 1;
            let d = (expected - actual).abs();
            if d > self.max_abs_diff {
                self.max_abs_diff = d;
            }
        }
    }
}

fn diff_cubics(expected: &serde_json::Value, actual: &[shapes::Cubic]) -> Diff {
    let mut diff = Diff { mismatched_bits: 0, max_abs_diff: 0. };
    let expected = expected.as_array().unwrap();
    assert_eq!(expected.len(), actual.len(), "cubic count mismatch");
    for (e, a) in expected.iter().zip(actual.iter()) {
        for (j, a) in a.points.iter().enumerate() {
            diff.add(f32_bits(&e[j]), *a);
        }
    }
    diff
}

fn assert_polygon_eq(name: &str, golden: &serde_json::Value, actual: &RoundedPolygon) {
    let diff = diff_cubics(&golden["cubics"], actual.cubics());
    // Tolerance: bit-exact is expected everywhere the computation has no
    // transcendental functions; those are allowed up to 1e-4 absolute.
    assert!(
        diff.max_abs_diff <= 1e-4,
        "{name}: {n} cubics differ by more than 1e-4 (max {d})",
        n = diff.mismatched_bits,
        d = diff.max_abs_diff
    );

    let center = golden["center"].as_array().unwrap();
    assert_eq!(f32_bits(&center[0]).to_bits(), actual.center_x().to_bits(), "{name}: centerX");
    assert_eq!(f32_bits(&center[1]).to_bits(), actual.center_y().to_bits(), "{name}: centerY");

    let bounds = golden["bounds"].as_array().unwrap();
    let actual_bounds = actual.calculate_bounds(true);
    for (i, b) in bounds.iter().enumerate() {
        assert!(
            (f32_bits(b) - actual_bounds[i]).abs() <= 1e-4,
            "{name}: bounds[{i}] expected {} got {}",
            f32_bits(b),
            actual_bounds[i]
        );
    }
    let max_bounds = golden["max_bounds"].as_array().unwrap();
    let actual_max_bounds = actual.calculate_max_bounds();
    for (i, b) in max_bounds.iter().enumerate() {
        assert!(
            (f32_bits(b) - actual_max_bounds[i]).abs() <= 1e-4,
            "{name}: max_bounds[{i}] expected {} got {}",
            f32_bits(b),
            actual_max_bounds[i]
        );
    }

    let features = golden["features"].as_array().unwrap();
    let actual_features = actual.features();
    assert_eq!(features.len(), actual_features.len(), "{name}: feature count");
    for (i, (f, a)) in features.iter().zip(actual_features.iter()).enumerate() {
        let (kind, convex, count) = match a {
            shapes::Feature::Edge(c) => ("edge", false, c.len()),
            shapes::Feature::Corner { cubics, convex } => ("corner", *convex, cubics.len()),
        };
        assert_eq!(f["kind"].as_str().unwrap(), kind, "{name}: feature {i} kind");
        assert_eq!(f["count"].as_u64().unwrap() as usize, count, "{name}: feature {i} cubic count");
        if kind == "corner" {
            assert_eq!(f["convex"].as_bool().unwrap(), convex, "{name}: feature {i} convex");
        }
    }
}

#[test]
fn material_shapes_parity() {
    let golden = load_golden("material_shapes.json");
    let shapes = golden["shapes"].as_object().unwrap();

    let actual: BTreeMap<_, _> = material::all()
        .into_iter()
        .chain(primitive_shapes())
        .map(|(n, p)| (n.to_string(), p))
        .collect();

    assert_eq!(shapes.len(), actual.len(), "shape count mismatch");
    for (name, golden_shape) in shapes {
        let polygon = actual.get(name).unwrap_or_else(|| panic!("missing shape {name}"));
        assert_polygon_eq(name, golden_shape, polygon);
    }
}

#[test]
fn morph_parity() {
    let golden = load_golden("morphs.json");
    let morphs = golden["morphs"].as_object().unwrap();

    let shapes: BTreeMap<_, _> = material::all().into_iter().collect();
    let built = |name: &str| -> RoundedPolygon {
        match name {
            "pill" => shapes::pill(2., 1., 0., Point::ZERO).unwrap(),
            "pill_star_8" => shapes::pill_star(
                2.,
                1.,
                8,
                0.5,
                CornerRounding::UNROUNDED,
                None,
                None,
                0.5,
                0.,
                Point::ZERO,
            )
            .unwrap(),
            _ => shapes
                .iter()
                .find_map(|(n, p)| (*n == name).then(|| p.clone()))
                .unwrap_or_else(|| panic!("missing shape {name}")),
        }
    };

    for (spec, progress_map) in morphs {
        let (from_name, to_name) = spec.split_once("->").unwrap();
        let morph = Morph::new(built(from_name), built(to_name));
        for (t_str, expected_cubics) in progress_map.as_object().unwrap() {
            let t: f32 = t_str.parse().unwrap();
            let cubics = morph.as_cubics(t);
            let diff = diff_cubics(expected_cubics, &cubics);
            assert!(
                diff.max_abs_diff <= 1e-4,
                "{spec} @ {t}: {n} cubics differ by more than 1e-4 (max {d})",
                n = diff.mismatched_bits,
                d = diff.max_abs_diff
            );
        }
    }
}
