// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Elevation } from "./elevation.slint";
import { BaseButton } from "./base_button.slint";
import { MaterialTypography } from "../styling/material_typography.slint";
import { MaterialPalette } from "../styling/material_palette.slint";
import { MaterialStyleMetrics } from "../styling/material_style_metrics.slint";
import {
    FabBaselineTokens,
    FabLargeTokens,
    FabPrimaryContainerTokens,
    FabSmallTokens,
} from "../styling/generated/material_component_tokens.slint";

export enum FABStyle {
    small,
    standard,
    large
}

export component FloatingActionButton {
    in property <image> icon <=> base.icon;
    in property <string> text <=> base.text;
    in property <string> tooltip <=> base.tooltip;
    in property <FABStyle> style;

    callback clicked <=> base.clicked;

    accessible-role: button;
    accessible-enabled: true;
    accessible-label: root.text == "" ? root.tooltip : root.text;
    accessible-action-default => { base.clicked(); }

    elevation := Elevation {
        border_radius: root.style == FABStyle.small ? FabSmallTokens.container_shape.top_left :
            root.style == FABStyle.standard ? FabBaselineTokens.container_shape.top_left : FabLargeTokens.container_shape.top_left;
        background: FabPrimaryContainerTokens.container_color;
        level: 3;
        width: 100%;
        height: 100%;
    }

    base := BaseButton {
        border_radius: elevation.border_radius;
        color:  FabPrimaryContainerTokens.icon_color;
        button_vertical_padding: root.style == FABStyle.small ? MaterialStyleMetrics.padding_10 :
            root.style == FABStyle.standard ? MaterialStyleMetrics.padding_14 : MaterialStyleMetrics.padding_30;
        button_horizontal_padding: self.button_vertical_padding;
        min_layout_width: self.min_layout_height;
        min_layout_height: root.style == FABStyle.small ? FabSmallTokens.container_height :
            root.style == FABStyle.standard ? FabBaselineTokens.container_height : FabLargeTokens.container_height;
        icon_size: root.style == FABStyle.small ? FabSmallTokens.icon_size :
            root.style == FABStyle.standard ? FabBaselineTokens.icon_size : FabLargeTokens.icon_size;
    }

    states [
        hover when base.has_hover : {
            elevation.level: 4;
        }
    ]
}
