# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

[package]
name = "vector-font-build-fail"
version = "0.0.0"
edition = "2021"
publish = false
license = "GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0"

[dependencies]
slint = { path = "../../../api/rs/slint", default-features = false, features = ["renderer-software", "libm", "unsafe-single-threaded", "compat-1-18"] }
