// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import {
    ToggleButton, FilledTonalToggleButton, ElevatedToggleButton, OutlinedToggleButton,
    IconToggleButton, FilledIconToggleButton, FilledTonalIconToggleButton, OutlinedIconToggleButton, ExtendedTouchArea,
} from "../../../ui-libraries/material/src/material.slint";

export component TestCase inherits Window {
    width: 300px;
    height: 480px;
    in-out property <bool> controls-enabled: true;
    out property <int> clicks;
    out property <bool> test: root.clicks == 32 && !root.controls-enabled;
    out property <bool> first-pressed: first.pressed;
    out property <bool> first-checked: first.checked;
    out property <bool> first-focused: first.has-focus;

    VerticalLayout {
        first := ToggleButton { text: "Filled"; enabled: root.controls-enabled; clicked => { root.clicks += 1; } }
        FilledTonalToggleButton { text: "Tonal"; enabled: root.controls-enabled; clicked => { root.clicks += 1; } }
        ElevatedToggleButton { text: "Elevated"; enabled: root.controls-enabled; clicked => { root.clicks += 1; } }
        OutlinedToggleButton { text: "Outlined"; enabled: root.controls-enabled; clicked => { root.clicks += 1; } }
        IconToggleButton { tooltip: "Icon"; enabled: root.controls-enabled; clicked => { root.clicks += 1; } }
        FilledIconToggleButton { tooltip: "Filled icon"; enabled: root.controls-enabled; clicked => { root.clicks += 1; } }
        FilledTonalIconToggleButton { tooltip: "Tonal icon"; enabled: root.controls-enabled; clicked => { root.clicks += 1; } }
        OutlinedIconToggleButton { tooltip: "Outlined icon"; enabled: root.controls-enabled; clicked => { root.clicks += 1; } }
    }
}

export component ExtendedCase inherits Window {
    width: 100px;
    height: 100px;
    in-out property <bool> controls-enabled: true;
    out property <bool> active: area.enter-pressed;
    out property <int> clicks;
    area := ExtendedTouchArea {
        enabled: root.controls-enabled;
        clicked => { root.clicks += 1; }
    }
}

export component ShapeCase inherits Window {
    width: 200px;
    height: 480px;
    out property <int> clicks;
    property <shape> diamond: Shapes.path("M0.5 0L1 0.5L0.5 1L0 0.5Z");

    VerticalLayout {
        ToggleButton { text: "Filled"; resting-shape: root.diamond; clicked => { root.clicks += 1; } }
        FilledTonalToggleButton { text: "Tonal"; resting-shape: root.diamond; clicked => { root.clicks += 1; } }
        ElevatedToggleButton { text: "Elevated"; resting-shape: root.diamond; clicked => { root.clicks += 1; } }
        OutlinedToggleButton { text: "Outlined"; resting-shape: root.diamond; clicked => { root.clicks += 1; } }
        IconToggleButton { tooltip: "Icon"; resting-shape: root.diamond; clicked => { root.clicks += 1; } }
        FilledIconToggleButton { tooltip: "Filled icon"; resting-shape: root.diamond; clicked => { root.clicks += 1; } }
        FilledTonalIconToggleButton { tooltip: "Tonal icon"; resting-shape: root.diamond; clicked => { root.clicks += 1; } }
        OutlinedIconToggleButton { tooltip: "Outlined icon"; resting-shape: root.diamond; clicked => { root.clicks += 1; } }
    }
}
