// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

package org.slint.material.parity

import org.json.JSONObject

/** One resolved parity scene: `scenes/<name>.json` as generated by
 * `material-parity-generator` (authored fields plus the ARGB `scheme` map and
 * `case_rel`, the reference directory under `references/`). */
class Scene(json: JSONObject) {
    val name: String = json.getString("name")
    val type: String = json.getString("type")
    val parity: String = json.getString("parity")
    val caseRel: String = json.getString("case_rel")
    val sizeDp: Pair<Int, Int> =
        json.getJSONArray("size").let { it.getInt(0) to it.getInt(1) }
    val densities: List<Int> =
        json.getJSONArray("densities").let { a -> (0 until a.length()).map(a::getInt) }
    val times: List<Long> =
        json.optJSONArray("times")?.let { a -> (0 until a.length()).map(a::getLong) }
            ?: emptyList()
    val traceProps: List<String> = stringList(json, "trace_props")
    val traceElements: List<String> = stringList(json, "trace_elements")
    val actions: List<Action> =
        json.optJSONArray("actions")?.let { a -> (0 until a.length()).map { Action(a.getJSONObject(it)) } }
            ?: emptyList()
    val widgets: List<Widget> =
        json.optJSONArray("widgets")?.let { a -> (0 until a.length()).map { Widget(a.getJSONObject(it)) } }
            ?: emptyList()
    val params: JSONObject = json.optJSONObject("params") ?: JSONObject()
    /** Authored theme inputs (seed/variant/spec/platform/dark/contrast) that
     * both scheme derivations consume. */
    val theme: JSONObject = json.optJSONObject("theme") ?: JSONObject()
    val scheme: Map<String, Long> =
        json.getJSONObject("scheme").let { s ->
            s.keys().asSequence().associateWith { s.getString(it).toLong(16) }
        }

    private fun stringList(json: JSONObject, key: String): List<String> =
        json.optJSONArray(key)?.let { a -> (0 until a.length()).map(a::getString) } ?: emptyList()

    /** Loads every scene named by the generated `scenes/index.txt` resource. */
    companion object {
        fun loadAll(): List<Scene> {
            val loader = Scene::class.java.classLoader
            return loader.getResourceAsStream("scenes/index.txt")!!.bufferedReader()
                .readLines()
                .filter { it.isNotBlank() }
                .map { name ->
                    Scene(JSONObject(loader.getResourceAsStream("scenes/$name.json")!!.bufferedReader().readText()))
                }
        }
    }
}

class Action(json: JSONObject) {
    val kind: String = json.getString("kind")
    val x: Float = json.getDouble("x").toFloat()
    val y: Float = json.getDouble("y").toFloat()
    /** Dispatch time within the frame sequence (ms); `0` fires right after
     * the pre-gesture baseline frame, as before. */
    val at: Long = json.optLong("at", 0)
    /** Sheet fling scenes: the release velocity in dp/s the Slint gesture
     * measures — the value the mirror feeds to the fling behavior. */
    val velocity: Float = json.optDouble("velocity", 0.0).toFloat()
}

class Widget(json: JSONObject) {
    val kind: String = json.getString("kind")
    val x: Float = json.optDouble("x", 0.0).toFloat()
    val y: Float = json.optDouble("y", 0.0).toFloat()
    val width: Float = json.optDouble("width", 0.0).toFloat()
    val height: Float = json.optDouble("height", 0.0).toFloat()
    val radius: Float = json.optDouble("radius", 0.0).toFloat()
    val text: String? = (json.opt("text") as? String)?.takeIf { it.isNotEmpty() }
    /** `alert-dialog`/`basic-alert-dialog`: the dialog title. */
    val title: String? = (json.opt("title") as? String)?.takeIf { it.isNotEmpty() }
    /** Stem of an svg under `src/ui/icons/` (`check` → `icons/check.svg`),
     * loaded as an [ImageVector] — the same path the Slint `Icons` image
     * rasterizes. */
    val icon: String? = (json.opt("icon") as? String)?.takeIf { it.isNotEmpty() }
    /** `connected-button`/`GroupItem.checked_icon`: swaps `icon` while the
     * item is checked (the upstream samples' filled/outlined swap). */
    val checkedIcon: String? = (json.opt("checked_icon") as? String)?.takeIf { it.isNotEmpty() }
    val enabled: Boolean = json.optBoolean("enabled", true)
    /** Interaction state the widget starts in: `enabled` (default),
     * `disabled`, `pressed` (pointer held), `hovered`, or `focused`. */
    val state: String = (json.opt("state") as? String)
        ?: (if (json.optBoolean("enabled", true)) "enabled" else "disabled")
    val color: String? = (json.opt("color") as? String)?.takeIf { it.isNotEmpty() }
    /** Button size bucket `xs`/`s`/`m`/`l`/`xl` — maps to the container
     * heights and [ToggleButtonSize]s; `s` is the upstream default. */
    val size: String = (json.opt("size") as? String) ?: "s"
    /** Button container corners: `round` (default stadium) or `square`. */
    val corner: String = (json.opt("corner") as? String) ?: "round"
    /** M3 elevation level (0–5) for `surface` widgets, mapped to
     * `Modifier.shadow`'s dp by `elevationDp`. */
    val level: Int = json.optInt("level", 0)
    /** Caster outline for `surface` widgets: a `MaterialShapes` member name
     * in kebab case (`"cookie-9-sided"` → `MaterialShapes.Cookie9Sided`), or
     * `"rect"` (default) for `radius`'s rounded rectangle. */
    val shape: String =
        if (json.isNull("shape")) "rect" else json.getString("shape")
    /** Toggle variant (`checkable` on the Slint side, `*ToggleButton`
     * composables upstream). */
    val checkable: Boolean = json.optBoolean("checkable", false)
    val checked: Boolean = json.optBoolean("checked", false)
    /** `checkbox`/`tri-state-checkbox` `ToggleableState` name —
     * `unchecked` (default), `checked`, `partially_checked`; a bare
     * `checked: true` resolves to `checked` on both sides. */
    val checkState: String = (json.opt("check_state") as? String)
        ?: (if (checked) "checked" else "unchecked")
    /** Icon-button container width `narrow`/`uniform`/`wide`. */
    val widthOption: String = (json.opt("width_option") as? String) ?: "uniform"
    /** `ListItem(onClick)` overload — `selectable`/`checkable` imply it. */
    val interactive: Boolean = json.optBoolean("interactive", false)
    /** `ListItem(selected, onClick)` overload. */
    val selectable: Boolean = json.optBoolean("selectable", false)
    val selected: Boolean = json.optBoolean("selected", false)
    /** `segmentedShapes(index, count)` position for `segmented-list-item`. */
    val index: Int = json.optInt("index", 0)
    val count: Int = json.optInt("count", 1)
    /** `overlineContent` text on a list item. */
    val overline: String? = (json.opt("overline") as? String)?.takeIf { it.isNotEmpty() }
    /** `supportingContent` text on a list item. */
    val supporting: String? = (json.opt("supporting") as? String)?.takeIf { it.isNotEmpty() }
    /** The `isSupportingMultiline` heuristic input to `ListItemType`. */
    val supportingMultiline: Boolean = json.optBoolean("supporting_multiline", false)
    /** 40px avatar circle with this label in the leading slot. */
    val avatar: String? = (json.opt("avatar") as? String)?.takeIf { it.isNotEmpty() }
    /** Icon stem (`Icons.*`) in the trailing slot — `icon` fills leading
     * on a list item; on a `*-split-button` it's the trailing-half chevron
     * (`keyboard_arrow_down` when unset). */
    val trailingIcon: String? = (json.opt("trailing_icon") as? String)?.takeIf { it.isNotEmpty() }
    val trailingText: String? = (json.opt("trailing_text") as? String)?.takeIf { it.isNotEmpty() }
    /** Icon stem used as the 56x56 `leading_image` source — both sides
     * rasterize the identical svg path clipped to the image shape. */
    val leadingImage: String? = (json.opt("leading_image") as? String)?.takeIf { it.isNotEmpty() }
    /** Loading-indicator mode: indeterminate (the continuous morph loop,
     * default) or driven by [progress]. */
    val indeterminate: Boolean = json.optBoolean("indeterminate", true)
    /** Determinate loading-indicator progress, 0–1. */
    val progress: Float = json.optDouble("progress", 0.0).toFloat()
    /** `top-app-bar` variant: `small` (default), `center`, `medium`,
     * `medium-flexible`, `large`, `large-flexible`, `two-rows`. */
    val variant: String = (json.opt("variant") as? String) ?: "small"
    val subtitle: String? = (json.opt("subtitle") as? String)?.takeIf { it.isNotEmpty() }
    /** `TopAppBarState.heightOffset`/`BottomAppBarState.heightOffset` —
     * negative values render a partially collapsed bar. */
    val heightOffset: Float = json.optDouble("height_offset", 0.0).toFloat()
    /** `TopAppBarState.contentOffset` — positive values mark the content
     * overlapped, flipping the single-row bar to its scrolled color. */
    val contentOffset: Float = json.optDouble("content_offset", 0.0).toFloat()
    val navIcon: String? = (json.opt("nav_icon") as? String)?.takeIf { it.isNotEmpty() }
    /** `top-app-bar` action / `bottom-app-bar` icon-button icon stems. */
    val icons: List<String> =
        json.optJSONArray("icons")?.let { a -> (0 until a.length()).map(a::getString) } ?: emptyList()
    val placeholder: String? = (json.opt("placeholder") as? String)?.takeIf { it.isNotEmpty() }
    /** `button-group` selection: `none` (clickable items, default),
     * `single`/`multiple` (toggle items). */
    val selection: String = (json.opt("selection") as? String) ?: "none"
    /** `button-group` `expanded-ratio` — `ButtonGroupDefaults.ExpandedRatio`. */
    val expandedRatio: Float = json.optDouble("expanded_ratio", 0.15).toFloat()
    /** `button-group` item a `pressed`/`hovered` `state` applies to. */
    val pressIndex: Int = json.optInt("press_index", 0)
    /** `*-split-button` kinds only: which half carries `state` and receives
     * the scripted pointer gesture — `leading` or `trailing`. */
    val side: String = (json.opt("side") as? String) ?: "trailing"
    /** `connected-button` only: `start`/`middle`/`end` — the position's
     * `connected*ButtonShapes`. `start` is the leading item of a horizontal
     * group, the top item of a vertical one. */
    val position: String = (json.opt("position") as? String) ?: "middle"
    /** `connected-button` only: the `VerticalButtonGroupSample` shapes —
     * `CornerSize(100)` caps on `start`/`end`, uniform 6dp pressed. */
    val vertical: Boolean = json.optBoolean("vertical", false)
    /** Group rows — `button-group` `clickableItem`/`toggleableItem` calls or
     * `connected-button-group`/`vertical-connected-button-group` items. */
    val items: List<GroupItem> =
        json.optJSONArray("items")?.let { a -> (0 until a.length()).map { GroupItem(a.getJSONObject(it)) } }
            ?: emptyList()
    /** Groups: every item carries its own checked state instead of one
     * [selectedIndex]. */
    val multiSelect: Boolean = json.optBoolean("multi_select", false)
    /** Single-select groups: the checked item (`-1` selects none); for
     * rails, the selected item index (`current-index` on the Slint side). */
    val selectedIndex: Int = json.optInt("selected_index", if (kind.contains("rail")) 0 else -1)
    /** `extended-fab` expansion state (`expanded` upstream); for rails,
     * `WideNavigationRailValue` — expanded when true, collapsed when false. */
    val expanded: Boolean = json.optBoolean("expanded", if (kind.contains("rail")) false else true)
    /** `fab`/`extended-fab` visibility — `visible` on
     * `Modifier.animateFloatingActionButton` upstream. */
    val shown: Boolean = json.optBoolean("shown", true)
    /** `animateFloatingActionButton` scale pivot — `Alignment` member name
     * in snake case (`bottom_end` default). */
    val alignment: String = (json.opt("alignment") as? String) ?: "bottom_end"
    /** `animateFloatingActionButton` `targetScale` (0.2 upstream). */
    val targetScale: Float = json.optDouble("target_scale", 0.2).toFloat()
    /** The prop a press+release click toggles — `expanded` or `shown`. */
    val toggle: String? = (json.opt("toggle") as? String)?.takeIf { it.isNotEmpty() }
    /** `extended-fab` label-slot width pin — `Modifier.width` on the
     * upstream `text` composable; 0/unset sizes it to the text. */
    val labelWidth: Float = json.optDouble("label_width", 0.0).toFloat()

    /** `date-picker`/`date-range-picker` initial `DisplayMode` —
     * `picker` (default) or `input`. */
    val displayMode: String = (json.opt("display_mode") as? String) ?: "picker"
    /** `date-picker` selected day — `DatePickerState.selectedDateMillis`
     * as an ISO `YYYY-MM-DD`. Shares the `selected` JSON key with the list
     * `Boolean` (per-kind value type), so it needs its own accessor name. */
    val selectedDate: String? = (json.opt("selected") as? String)?.takeIf { it.isNotEmpty() }
    /** `date-range-picker` selection bounds — `selectedStartDateMillis`
     * and `selectedEndDateMillis` as ISO dates. */
    val selectedStart: String? =
        (json.opt("selected_start") as? String)?.takeIf { it.isNotEmpty() }
    val selectedEnd: String? = (json.opt("selected_end") as? String)?.takeIf { it.isNotEmpty() }
    /** `displayedMonthMillis` — ISO `YYYY-MM-DD` or `YYYY-MM` (day 1). */
    val displayed: String? = (json.opt("displayed") as? String)?.takeIf { it.isNotEmpty() }
    /** `SelectableDates` window the mirror implements as a contiguous
     * millis range — ISO dates; a missing bound is unrestricted. */
    val selectableFrom: String? =
        (json.opt("selectable_from") as? String)?.takeIf { it.isNotEmpty() }
    val selectableTo: String? =
        (json.opt("selectable_to") as? String)?.takeIf { it.isNotEmpty() }
    /** `yearRange` on the picker state — the upstream default 1900–2100. */
    val yearMin: Int = json.optInt("year_min", 1900)
    val yearMax: Int = json.optInt("year_max", 2100)
    /** `showModeToggle` on `DatePicker`/`DateRangePicker`. */
    val showModeToggle: Boolean = json.optBoolean("show_mode_toggle", true)
    /** The dialog's confirm `TextButton` enabled state. */
    val confirmEnabled: Boolean = json.optBoolean("confirm_enabled", true)

    /** `*-divider` line thickness in dp — `DividerDefaults.Thickness` when
     * unset; `0` is the upstream `Dp.Hairline` (one physical pixel). */
    val thickness: Float = json.optDouble("thickness", 1.0).toFloat()

    // --- navigation-rail kinds (`navigation-rail`, `wide-navigation-rail`,
    // `modal-navigation-rail`) ---
    /** Rail items: `[{ "text": "Inbox", "icon": "inbox",
     * "selected_icon": "inbox", "badge": "3", "enabled": false }]`.
     * `rail_items` in the scene JSON — `items` is `button-group`'s
     * `GroupItem` rows. */
    val railItems: List<RailItem> =
        json.optJSONArray("rail_items")?.let { a -> (0 until a.length()).map { RailItem(a.getJSONObject(it)) } }
            ?: emptyList()
    /** `ModalWideNavigationRail`'s `hideOnCollapse` — the standalone modal
     * sheet that slides in instead of keeping a persistent rail. */
    val hideOnCollapse: Boolean = json.optBoolean("hide_on_collapse", false)
    /** `Arrangement.Vertical` of the rail's item stack: `top` (default),
     * `center`, `bottom`, `space-evenly`, `space-between`, `space-around`. */
    val arrangement: String = (json.opt("arrangement") as? String) ?: "top"
    /** FAB icon stem in the rail header. */
    val fabIcon: String? = (json.opt("fab_icon") as? String)?.takeIf { it.isNotEmpty() }

    val isFab: Boolean get() = kind == "fab" || kind == "extended-fab"
    val isSplitButton: Boolean get() = kind.endsWith("split-button")
    // --- navigation-rail / navigation-bar kinds ---
    /** `NavigationRailItem.alwaysShowLabel` / `NavigationBarItem.alwaysShowLabel`
     * — narrow rail and tall navigation bar only. */
    val alwaysShowLabel: Boolean = json.optBoolean("always_show_label", true)
    /** `ShortNavigationBarArrangement` — `equal-weight` (default) or
     * `centered`. */
    val navArrangement: String = (json.opt("nav_arrangement") as? String) ?: "equal-weight"
    /** `NavigationItemIconPosition` — `top` (default) or `start`. */
    val iconPosition: String = (json.opt("icon_position") as? String) ?: "top"

    val isIconButton: Boolean get() = kind.endsWith("icon-button")
    val isButton: Boolean get() =
        (isIconButton || isSplitButton || kind.endsWith("-button")) && kind != "connected-button"
    val isListItem: Boolean get() = kind == "list-item" || kind == "segmented-list-item"
    /** `elevated-rect` only: the elevation in dp of the Android ambient+spot
     * shadow `Modifier.shadow` draws behind the caster. */
    val elevation: Float = json.optDouble("elevation", 0.0).toFloat()
    /** Sheet kinds: the `sheetContent` rect's measured height in dp. */
    val sheetHeight: Float = json.optDouble("sheet_height", 120.0).toFloat()
    /** `bottom-sheet-scaffold` only: `sheetPeekHeight` (56 dp default). */
    val peekHeight: Float = json.optDouble("peek_height", 56.0).toFloat()
    /** Sheet kinds: `initialValue` — `hidden`, `partially-expanded`,
     * `expanded`. */
    val initial: String = (json.opt("initial") as? String) ?: "hidden"
    /** Sheet kinds: `skipPartiallyExpanded`. */
    val skipPartial: Boolean = json.optBoolean("skip_partial", false)
    /** `bottom-sheet-scaffold` only: `skipHiddenState` (default true). */
    val skipHidden: Boolean = json.optBoolean("skip_hidden", true)
    /** Sheet kinds: `gesturesEnabled`/`sheetSwipeEnabled` (default true). */
    val gestures: Boolean = json.optBoolean("gestures", true)
    /** Sheet kinds: scheme role for the sheet content rect. */
    val contentColor: String = (json.opt("content_color") as? String) ?: "tertiary-container"
    /** `bottom-sheet-scaffold` only: scheme role for the scaffold body. */
    val bodyColor: String = (json.opt("body_color") as? String) ?: "surface"
    /** Sheet kinds: the M3 elevation level for `sheet-elevation-level`/
     * `sheetShadowElevation` (-1 = the pinned default; scenes pass 0 —
     * platform shadows deadlock layoutlib and shadow parity lives in the
     * elevation scenes). */
    val sheetElevation: Int = json.optInt("sheet_elevation", -1)
    /** `material-surface`: upstream `tonalElevation` in dp. */
    val tonalElevation: Float = json.optDouble("tonal_elevation", 0.0).toFloat()
    /** `material-surface`: the ambient `LocalAbsoluteTonalElevation` a parent
     * Surface would provide (dp). */
    val parentElevation: Float = json.optDouble("parent_elevation", 0.0).toFloat()
    /** `material-surface`: `BorderStroke` width (dp) + palette-role color
     * (`outline` default). */
    val borderWidth: Float = json.optDouble("border_width", 0.0).toFloat()
    val borderColor: String? = (json.opt("border_color") as? String)?.takeIf { it.isNotEmpty() }
    /** `material-surface` overloads: `clickable`/`toggleable` — `selectable`
     * and `selected` are declared above with the list-item overloads. */
    val clickable: Boolean = json.optBoolean("clickable", false)
    val toggleable: Boolean = json.optBoolean("toggleable", false)
}

/** One rail item (`NavigationItem` on the Slint side): `{ "text": "Inbox",
 * "icon": "inbox", "selected_icon": "inbox", "badge": "3",
 * "enabled": false }`. */
class RailItem(json: JSONObject) {
    val text: String = json.optString("text", "")
    val icon: String? = (json.opt("icon") as? String)?.takeIf { it.isNotEmpty() }
    val selectedIcon: String? =
        (json.opt("selected_icon") as? String)?.takeIf { it.isNotEmpty() }
    val badge: String? = (json.opt("badge") as? String)?.takeIf { it.isNotEmpty() }
    val enabled: Boolean = json.optBoolean("enabled", true)
}

/** One group item — the arguments an upstream `clickableItem`/
 * `toggleableItem` (standard `button-group`) or a `connected-button-group`
 * item takes: the label, an optional leading `icon`, a `checked_icon` swap
 * while checked, a `weight` width share, `disabled`/`enabled`, `checked`,
 * and an interaction `state` emitted on the item's own `InteractionSource`. */
class GroupItem(json: JSONObject) {
    val text: String = json.optString("text", "")
    /** Icon stem under `src/ui/icons/` — loaded like a widget's `icon`. */
    val icon: String? = (json.opt("icon") as? String)?.takeIf { it.isNotEmpty() }
    val checkedIcon: String? = (json.opt("checked_icon") as? String)?.takeIf { it.isNotEmpty() }
    /** Weighted width share; `null` → upstream's `Float.NaN` (unweighted). */
    val weight: Float? =
        if (!json.isNull("weight")) json.getDouble("weight").toFloat() else null
    val disabled: Boolean = json.optBoolean("disabled", false)
    val enabled: Boolean = json.optBoolean("enabled", true)
    val checked: Boolean = json.optBoolean("checked", false)
    /** `enabled` (default), `pressed`, `hovered`, or `focused`. */
    val state: String = (json.opt("state") as? String) ?: "enabled"
    /** The item participates when both sides' enable flags say so. */
    fun isEnabled() = enabled && !disabled
    // --- rail / navigation-bar item fields ---
    val selectedIcon: String? =
        (json.opt("selected_icon") as? String)?.takeIf { it.isNotEmpty() }
    val badge: String? = (json.opt("badge") as? String)?.takeIf { it.isNotEmpty() }
}

/** "primary-container" → "primaryContainer" for `scheme` map lookups. */
fun String.kebabToCamel(): String =
    split('-').mapIndexed { i, part -> if (i == 0) part else part.replaceFirstChar(Char::uppercaseChar) }
        .joinToString("")
