// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

package org.slint.material.parity

import org.json.JSONObject

/** One resolved parity scene: `scenes/<name>.json` as generated by
 * `material-parity-generator` (authored fields plus the ARGB `scheme` map and
 * `case_rel`, the reference directory under `references/`). */
class Scene(json: JSONObject) {
    val name: String = json.getString("name")
    val type: String = json.getString("type")
    val parity: String = json.getString("parity")
    val caseRel: String = json.getString("case_rel")
    val sizeDp: Pair<Int, Int> =
        json.getJSONArray("size").let { it.getInt(0) to it.getInt(1) }
    val densities: List<Int> =
        json.getJSONArray("densities").let { a -> (0 until a.length()).map(a::getInt) }
    val times: List<Long> =
        json.optJSONArray("times")?.let { a -> (0 until a.length()).map(a::getLong) }
            ?: emptyList()
    val traceProps: List<String> = stringList(json, "trace_props")
    val traceElements: List<String> = stringList(json, "trace_elements")
    val actions: List<Action> =
        json.optJSONArray("actions")?.let { a -> (0 until a.length()).map { Action(a.getJSONObject(it)) } }
            ?: emptyList()
    val widgets: List<Widget> =
        json.optJSONArray("widgets")?.let { a -> (0 until a.length()).map { Widget(a.getJSONObject(it)) } }
            ?: emptyList()
    val params: JSONObject = json.optJSONObject("params") ?: JSONObject()
    /** Authored theme inputs (seed/variant/spec/platform/dark/contrast) that
     * both scheme derivations consume. */
    val theme: JSONObject = json.optJSONObject("theme") ?: JSONObject()
    val scheme: Map<String, Long> =
        json.getJSONObject("scheme").let { s ->
            s.keys().asSequence().associateWith { s.getString(it).toLong(16) }
        }

    private fun stringList(json: JSONObject, key: String): List<String> =
        json.optJSONArray(key)?.let { a -> (0 until a.length()).map(a::getString) } ?: emptyList()

    /** Loads every scene named by the generated `scenes/index.txt` resource. */
    companion object {
        fun loadAll(): List<Scene> {
            val loader = Scene::class.java.classLoader
            return loader.getResourceAsStream("scenes/index.txt")!!.bufferedReader()
                .readLines()
                .filter { it.isNotBlank() }
                .map { name ->
                    Scene(JSONObject(loader.getResourceAsStream("scenes/$name.json")!!.bufferedReader().readText()))
                }
        }
    }
}

class Action(json: JSONObject) {
    val kind: String = json.getString("kind")
    val x: Float = json.getDouble("x").toFloat()
    val y: Float = json.getDouble("y").toFloat()
    /** Dispatch time within the frame sequence (ms); `0` fires right after
     * the pre-gesture baseline frame, as before. */
    val at: Long = json.optLong("at", 0)
}

class Widget(json: JSONObject) {
    val kind: String = json.getString("kind")
    val x: Float = json.optDouble("x", 0.0).toFloat()
    val y: Float = json.optDouble("y", 0.0).toFloat()
    val width: Float = json.optDouble("width", 0.0).toFloat()
    val height: Float = json.optDouble("height", 0.0).toFloat()
    val radius: Float = json.optDouble("radius", 0.0).toFloat()
    val text: String? = (json.opt("text") as? String)?.takeIf { it.isNotEmpty() }
    /** Stem of an svg under `src/ui/icons/` (`check` → `icons/check.svg`),
     * loaded as an [ImageVector] — the same path the Slint `Icons` image
     * rasterizes. */
    val icon: String? = (json.opt("icon") as? String)?.takeIf { it.isNotEmpty() }
    val enabled: Boolean = json.optBoolean("enabled", true)
    /** Interaction state the widget starts in: `enabled` (default),
     * `disabled`, `pressed` (pointer held), `hovered`, or `focused`. */
    val state: String = (json.opt("state") as? String)
        ?: (if (json.optBoolean("enabled", true)) "enabled" else "disabled")
    val color: String? = (json.opt("color") as? String)?.takeIf { it.isNotEmpty() }
    /** Button size bucket `xs`/`s`/`m`/`l`/`xl` — maps to the container
     * heights and [ToggleButtonSize]s; `s` is the upstream default. */
    val size: String = (json.opt("size") as? String) ?: "s"
    /** Button container corners: `round` (default stadium) or `square`. */
    val corner: String = (json.opt("corner") as? String) ?: "round"
    /** M3 elevation level (0–5) for `surface` widgets, mapped to
     * `Modifier.shadow`'s dp by `elevationDp`. */
    val level: Int = json.optInt("level", 0)
    /** Caster outline for `surface` widgets: a `MaterialShapes` member name
     * in kebab case (`"cookie-9-sided"` → `MaterialShapes.Cookie9Sided`), or
     * `"rect"` (default) for `radius`'s rounded rectangle. */
    val shape: String =
        if (json.isNull("shape")) "rect" else json.getString("shape")
    /** Toggle variant (`checkable` on the Slint side, `*ToggleButton`
     * composables upstream). */
    val checkable: Boolean = json.optBoolean("checkable", false)
    val checked: Boolean = json.optBoolean("checked", false)
    /** Icon-button container width `narrow`/`uniform`/`wide`. */
    val widthOption: String = (json.opt("width_option") as? String) ?: "uniform"
    /** `ListItem(onClick)` overload — `selectable`/`checkable` imply it. */
    val interactive: Boolean = json.optBoolean("interactive", false)
    /** `ListItem(selected, onClick)` overload. */
    val selectable: Boolean = json.optBoolean("selectable", false)
    val selected: Boolean = json.optBoolean("selected", false)
    /** `segmentedShapes(index, count)` position for `segmented-list-item`. */
    val index: Int = json.optInt("index", 0)
    val count: Int = json.optInt("count", 1)
    /** `overlineContent` text on a list item. */
    val overline: String? = (json.opt("overline") as? String)?.takeIf { it.isNotEmpty() }
    /** `supportingContent` text on a list item. */
    val supporting: String? = (json.opt("supporting") as? String)?.takeIf { it.isNotEmpty() }
    /** The `isSupportingMultiline` heuristic input to `ListItemType`. */
    val supportingMultiline: Boolean = json.optBoolean("supporting_multiline", false)
    /** 40px avatar circle with this label in the leading slot. */
    val avatar: String? = (json.opt("avatar") as? String)?.takeIf { it.isNotEmpty() }
    /** Icon stem (`Icons.*`) in the trailing slot; `icon` fills leading. */
    val trailingIcon: String? = (json.opt("trailing_icon") as? String)?.takeIf { it.isNotEmpty() }
    val trailingText: String? = (json.opt("trailing_text") as? String)?.takeIf { it.isNotEmpty() }
    /** Icon stem used as the 56x56 `leading_image` source — both sides
     * rasterize the identical svg path clipped to the image shape. */
    val leadingImage: String? = (json.opt("leading_image") as? String)?.takeIf { it.isNotEmpty() }

    val isIconButton: Boolean get() = kind.endsWith("icon-button")
    val isButton: Boolean get() = isIconButton || kind.endsWith("-button")
    val isListItem: Boolean get() = kind == "list-item" || kind == "segmented-list-item"
}

/** "primary-container" → "primaryContainer" for `scheme` map lookups. */
fun String.kebabToCamel(): String =
    split('-').mapIndexed { i, part -> if (i == 0) part else part.replaceFirstChar(Char::uppercaseChar) }
        .joinToString("")
