// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

package org.slint.material.parity

import org.json.JSONObject

/** One resolved parity scene: `scenes/<name>.json` as generated by
 * `material-parity-generator` (authored fields plus the ARGB `scheme` map and
 * `case_rel`, the reference directory under `references/`). */
class Scene(json: JSONObject) {
    val name: String = json.getString("name")
    val type: String = json.getString("type")
    val parity: String = json.getString("parity")
    val caseRel: String = json.getString("case_rel")
    val sizeDp: Pair<Int, Int> =
        json.getJSONArray("size").let { it.getInt(0) to it.getInt(1) }
    val densities: List<Int> =
        json.getJSONArray("densities").let { a -> (0 until a.length()).map(a::getInt) }
    val times: List<Long> =
        json.optJSONArray("times")?.let { a -> (0 until a.length()).map(a::getLong) }
            ?: emptyList()
    val traceProps: List<String> = stringList(json, "trace_props")
    val traceElements: List<String> = stringList(json, "trace_elements")
    val actions: List<Action> =
        json.optJSONArray("actions")?.let { a -> (0 until a.length()).map { Action(a.getJSONObject(it)) } }
            ?: emptyList()
    val widgets: List<Widget> =
        json.optJSONArray("widgets")?.let { a -> (0 until a.length()).map { Widget(a.getJSONObject(it)) } }
            ?: emptyList()
    val params: JSONObject = json.optJSONObject("params") ?: JSONObject()
    /** Authored theme inputs (seed/variant/spec/platform/dark/contrast) that
     * both scheme derivations consume. */
    val theme: JSONObject = json.optJSONObject("theme") ?: JSONObject()
    val scheme: Map<String, Long> =
        json.getJSONObject("scheme").let { s ->
            s.keys().asSequence().associateWith { s.getString(it).toLong(16) }
        }

    private fun stringList(json: JSONObject, key: String): List<String> =
        json.optJSONArray(key)?.let { a -> (0 until a.length()).map(a::getString) } ?: emptyList()

    /** Loads every scene named by the generated `scenes/index.txt` resource. */
    companion object {
        fun loadAll(): List<Scene> {
            val loader = Scene::class.java.classLoader
            return loader.getResourceAsStream("scenes/index.txt")!!.bufferedReader()
                .readLines()
                .filter { it.isNotBlank() }
                .map { name ->
                    Scene(JSONObject(loader.getResourceAsStream("scenes/$name.json")!!.bufferedReader().readText()))
                }
        }
    }
}

class Action(json: JSONObject) {
    val kind: String = json.getString("kind")
    val x: Float = json.getDouble("x").toFloat()
    val y: Float = json.getDouble("y").toFloat()
}

class Widget(json: JSONObject) {
    val kind: String = json.getString("kind")
    val x: Float = json.optDouble("x", 0.0).toFloat()
    val y: Float = json.optDouble("y", 0.0).toFloat()
    val width: Float = json.optDouble("width", 0.0).toFloat()
    val height: Float = json.optDouble("height", 0.0).toFloat()
    val radius: Float = json.optDouble("radius", 0.0).toFloat()
    val text: String? = json.optString("text").takeIf { it.isNotEmpty() }
    val enabled: Boolean = json.optBoolean("enabled", true)
    /** Interaction state the widget starts in: `enabled` (default),
     * `disabled`, `pressed` (pointer held), `hovered`, or `focused`. */
    val state: String = json.optString("state", if (json.optBoolean("enabled", true)) "enabled" else "disabled")
    val color: String? = json.optString("color").takeIf { it.isNotEmpty() }
    /** M3 elevation level (0–5) for `surface` widgets, mapped to
     * `Modifier.shadow`'s dp by `elevationDp`. */
    val level: Int = json.optInt("level", 0)
    /** Caster outline for `surface` widgets: a `MaterialShapes` member name
     * in kebab case (`"cookie-9-sided"` → `MaterialShapes.Cookie9Sided`), or
     * `"rect"` (default) for `radius`'s rounded rectangle. */
    val shape: String =
        if (json.isNull("shape")) "rect" else json.getString("shape")
}

/** "primary-container" → "primaryContainer" for `scheme` map lookups. */
fun String.kebabToCamel(): String =
    split('-').mapIndexed { i, part -> if (i == 0) part else part.replaceFirstChar(Char::uppercaseChar) }
        .joinToString("")
