// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Bit-exact test vectors, generated by `vectors/generate.sh` from the
//! Java implementation of material-color-utilities at the pinned commit
//! (material-foundation/material-color-utilities @
//! 5b3618b16fdc3825e21d5679bafd144662088ea1), compiled with `Math.*`
//! rewritten to `StrictMath.*` so the results are the canonical fdlibm
//! values rather than HotSpot JIT intrinsics.

use std::io::Read;

use material_color_utils::Argb;
use material_color_utils::blend::Blend;
use material_color_utils::contrast::Contrast;
use material_color_utils::dislike::DislikeAnalyzer;
use material_color_utils::dynamiccolor::{
    DynamicColor, DynamicScheme, Platform, SpecVersion, Variant,
};
use material_color_utils::hct::Hct;
use material_color_utils::palettes::TonalPalette;
use material_color_utils::quantize::{QuantizerCelebi, QuantizerResult};
use material_color_utils::scheme::*;
use material_color_utils::score::Score;
use material_color_utils::temperature::TemperatureCache;

fn parse_argb(s: &str) -> Argb {
    Argb::from_str_radix(s.strip_prefix("0x").unwrap(), 16).unwrap()
}
fn parse_f64_bits(s: &str) -> f64 {
    f64::from_bits(u64::from_str_radix(s.strip_prefix("f:").unwrap(), 16).unwrap())
}
fn fbits(x: f64) -> u64 {
    x.to_bits()
}

fn scheme_for(
    variant: Variant,
    seeds: &[Argb],
    dark: bool,
    cl: f64,
    spec: SpecVersion,
    platform: Platform,
) -> DynamicScheme {
    let hcts: Vec<Hct> = seeds.iter().map(|&a| Hct::from_int(a)).collect();
    let n = |ctor: fn(Vec<Hct>, bool, f64, SpecVersion, Platform) -> DynamicScheme| {
        ctor(hcts.clone(), dark, cl, spec, platform)
    };
    match variant {
        Variant::Monochrome => n(SchemeMonochrome::new),
        Variant::Neutral => n(SchemeNeutral::new),
        Variant::TonalSpot => n(SchemeTonalSpot::new),
        Variant::Vibrant => n(SchemeVibrant::new),
        Variant::Expressive => n(SchemeExpressive::new),
        Variant::Fidelity => n(SchemeFidelity::new),
        Variant::Content => n(SchemeContent::new),
        Variant::Rainbow => n(SchemeRainbow::new),
        Variant::FruitSalad => n(SchemeFruitSalad::new),
        Variant::Cmf => n(SchemeCmf::new),
    }
}

fn token_color(s: &DynamicScheme, token: &str) -> DynamicColor {
    let c = s.colors();
    match token {
        "primaryPaletteKeyColor" => c.primary_palette_key_color(),
        "secondaryPaletteKeyColor" => c.secondary_palette_key_color(),
        "tertiaryPaletteKeyColor" => c.tertiary_palette_key_color(),
        "neutralPaletteKeyColor" => c.neutral_palette_key_color(),
        "neutralVariantPaletteKeyColor" => c.neutral_variant_palette_key_color(),
        "errorPaletteKeyColor" => c.error_palette_key_color(),
        "background" => c.background(),
        "onBackground" => c.on_background(),
        "surface" => c.surface(),
        "surfaceDim" => c.surface_dim(),
        "surfaceBright" => c.surface_bright(),
        "surfaceContainerLowest" => c.surface_container_lowest(),
        "surfaceContainerLow" => c.surface_container_low(),
        "surfaceContainer" => c.surface_container(),
        "surfaceContainerHigh" => c.surface_container_high(),
        "surfaceContainerHighest" => c.surface_container_highest(),
        "onSurface" => c.on_surface(),
        "surfaceVariant" => c.surface_variant(),
        "onSurfaceVariant" => c.on_surface_variant(),
        "inverseSurface" => c.inverse_surface(),
        "inverseOnSurface" => c.inverse_on_surface(),
        "outline" => c.outline(),
        "outlineVariant" => c.outline_variant(),
        "shadow" => c.shadow(),
        "scrim" => c.scrim(),
        "surfaceTint" => c.surface_tint(),
        "primary" => c.primary(),
        "primaryDim" => c.primary_dim().expect("primaryDim"),
        "onPrimary" => c.on_primary(),
        "primaryContainer" => c.primary_container(),
        "onPrimaryContainer" => c.on_primary_container(),
        "primaryFixed" => c.primary_fixed(),
        "primaryFixedDim" => c.primary_fixed_dim(),
        "onPrimaryFixed" => c.on_primary_fixed(),
        "onPrimaryFixedVariant" => c.on_primary_fixed_variant(),
        "inversePrimary" => c.inverse_primary(),
        "secondary" => c.secondary(),
        "secondaryDim" => c.secondary_dim().expect("secondaryDim"),
        "onSecondary" => c.on_secondary(),
        "secondaryContainer" => c.secondary_container(),
        "onSecondaryContainer" => c.on_secondary_container(),
        "secondaryFixed" => c.secondary_fixed(),
        "secondaryFixedDim" => c.secondary_fixed_dim(),
        "onSecondaryFixed" => c.on_secondary_fixed(),
        "onSecondaryFixedVariant" => c.on_secondary_fixed_variant(),
        "tertiary" => c.tertiary(),
        "tertiaryDim" => c.tertiary_dim().expect("tertiaryDim"),
        "onTertiary" => c.on_tertiary(),
        "tertiaryContainer" => c.tertiary_container(),
        "onTertiaryContainer" => c.on_tertiary_container(),
        "tertiaryFixed" => c.tertiary_fixed(),
        "tertiaryFixedDim" => c.tertiary_fixed_dim(),
        "onTertiaryFixed" => c.on_tertiary_fixed(),
        "onTertiaryFixedVariant" => c.on_tertiary_fixed_variant(),
        "error" => c.error(),
        "errorDim" => c.error_dim().expect("errorDim"),
        "onError" => c.on_error(),
        "errorContainer" => c.error_container(),
        "onErrorContainer" => c.on_error_container(),
        t => panic!("unknown token {t}"),
    }
}

fn variant(name: &str) -> Variant {
    match name {
        "monochrome" => Variant::Monochrome,
        "neutral" => Variant::Neutral,
        "tonal_spot" => Variant::TonalSpot,
        "vibrant" => Variant::Vibrant,
        "expressive" => Variant::Expressive,
        "fidelity" => Variant::Fidelity,
        "content" => Variant::Content,
        "rainbow" => Variant::Rainbow,
        "fruit_salad" => Variant::FruitSalad,
        "cmf" => Variant::Cmf,
        n => panic!("unknown variant {n}"),
    }
}

fn spec(name: &str) -> SpecVersion {
    match name {
        "2021" => SpecVersion::Spec2021,
        "2025" => SpecVersion::Spec2025,
        "2026" => SpecVersion::Spec2026,
        n => panic!("unknown spec {n}"),
    }
}

#[test]
fn vectors() {
    let mut text = String::new();
    flate2::read::GzDecoder::new(&include_bytes!("vectors/vectors.txt.gz")[..])
        .read_to_string(&mut text)
        .unwrap();
    let text = text.as_str();
    let mut failures = 0;
    let mut checked = 0u32;
    // Cache of the current scheme; scheme lines are grouped so we rebuild
    // only when the key changes.
    let mut current_key = String::new();
    let mut current_scheme: Option<DynamicScheme> = None;
    for (lineno, line) in text.lines().enumerate() {
        let lineno = lineno + 1;
        let (fields, expected) = line.rsplit_once(" = ").unwrap();
        let f: Vec<&str> = fields.split_whitespace().collect();
        match f[0] {
            "scheme" => {
                // scheme <variant> <spec> <contrast> <dark> <platform> <seed> <seed2|-> <token>
                let key = f[1..8].join(" ");
                if key != current_key {
                    let v = variant(f[1]);
                    let seeds: Vec<Argb> = if f[7] == "-" {
                        vec![parse_argb(f[6])]
                    } else {
                        vec![parse_argb(f[6]), parse_argb(f[7])]
                    };
                    current_scheme = Some(scheme_for(
                        v,
                        &seeds,
                        f[4] == "1",
                        f[3].parse().unwrap(),
                        spec(f[2]),
                        match f[5] {
                            "phone" => Platform::Phone,
                            "watch" => Platform::Watch,
                            p => panic!("platform {p}"),
                        },
                    ));
                    current_key = key;
                }
                let s = current_scheme.as_ref().unwrap();
                let got = s.get_argb(&token_color(s, f[8]));
                let want = parse_argb(expected);
                if got != want {
                    failures += 1;
                    if failures < 10000 {
                        eprintln!("line {lineno}: {fields} -> got 0x{got:016x} want {expected}");
                    }
                }
                checked += 1;
            }
            "hct" => {
                let h = Hct::from_int(parse_argb(f[1]));
                let e: Vec<&str> = expected.split_whitespace().collect();
                if fbits(h.hue()) != parse_f64_bits(e[0]).to_bits()
                    || fbits(h.chroma()) != parse_f64_bits(e[1]).to_bits()
                    || fbits(h.tone()) != parse_f64_bits(e[2]).to_bits()
                    || h.to_int() != parse_argb(e[3])
                {
                    failures += 1;
                    eprintln!(
                        "line {lineno}: {fields} got {:016x} {:016x} {:016x} {:016x}",
                        h.hue().to_bits(),
                        h.chroma().to_bits(),
                        h.tone().to_bits(),
                        h.to_int() as u64,
                    );
                }
                checked += 1;
            }
            "hct_from" => {
                let h =
                    Hct::from(f[1].parse().unwrap(), f[2].parse().unwrap(), f[3].parse().unwrap());
                if h.to_int() != parse_argb(expected) {
                    failures += 1;
                    eprintln!("line {lineno}: {fields} got 0x{:x} want {expected}", h.to_int());
                }
                checked += 1;
            }
            "palette" | "palette_hc" => {
                let p = if f[0] == "palette" {
                    TonalPalette::from_int(parse_argb(f[1]))
                } else {
                    TonalPalette::from_hue_and_chroma(f[1].parse().unwrap(), f[2].parse().unwrap())
                };
                let wants: Vec<Argb> = expected.split_whitespace().map(parse_argb).collect();
                for (t, &want) in wants.iter().enumerate() {
                    let got = p.tone(t as i64);
                    if got != want {
                        failures += 1;
                        if failures < 10000 {
                            eprintln!(
                                "line {lineno}: {fields} tone {t} got 0x{got:016x} want 0x{want:016x}"
                            );
                        }
                    }
                    checked += 1;
                }
            }
            "harmonize" => {
                let got = Blend::harmonize(parse_argb(f[1]), parse_argb(f[2]));
                if got != parse_argb(expected) {
                    failures += 1;
                    eprintln!("line {lineno}: {fields} got 0x{got:016x} want {expected}");
                }
                checked += 1;
            }
            "cam16_ucs" => {
                let got = Blend::cam16_ucs(parse_argb(f[1]), parse_argb(f[2]), 0.5);
                if got != parse_argb(expected) {
                    failures += 1;
                    eprintln!("line {lineno}: {fields} got 0x{got:016x} want {expected}");
                }
                checked += 1;
            }
            "hct_hue" => {
                let got = Blend::hct_hue(parse_argb(f[1]), parse_argb(f[2]), 90.0);
                if got != parse_argb(expected) {
                    failures += 1;
                    eprintln!("line {lineno}: {fields} got 0x{got:016x} want {expected}");
                }
                checked += 1;
            }
            "dislike" => {
                let got =
                    DislikeAnalyzer::fix_if_disliked(Hct::from_int(parse_argb(f[1]))).to_int();
                if got != parse_argb(expected) {
                    failures += 1;
                    eprintln!("line {lineno}: {fields} got 0x{got:016x} want {expected}");
                }
                checked += 1;
            }
            "temperature" => {
                let cache = TemperatureCache::new(Hct::from_int(parse_argb(f[1])));
                let e: Vec<&str> = expected.split_whitespace().collect();
                let mut got = vec![cache.complement().to_int()];
                got.extend(cache.get_analogous_colors(5, 12).iter().map(|h| h.to_int()));
                let want: Vec<Argb> = e.iter().map(|&s| parse_argb(s)).collect();
                if got != want {
                    failures += 1;
                    eprintln!("line {lineno}: {fields} got {got:x?} want {want:x?}");
                }
                checked += 1;
            }
            "contrast_tone" => {
                let got = Contrast::ratio_of_tones(f[1].parse().unwrap(), f[2].parse().unwrap());
                if got.to_bits() != parse_f64_bits(expected).to_bits() {
                    failures += 1;
                    eprintln!("line {lineno}: {fields} got {got} want {expected}");
                }
                checked += 1;
            }
            "contrast_ld" => {
                let tone: f64 = f[1].parse().unwrap();
                let ratio: f64 = f[2].parse().unwrap();
                let e: Vec<&str> = expected.split_whitespace().collect();
                let l = Contrast::lighter_unsafe(tone, ratio);
                let d = Contrast::darker_unsafe(tone, ratio);
                if l.to_bits() != parse_f64_bits(e[0]).to_bits()
                    || d.to_bits() != parse_f64_bits(e[1]).to_bits()
                {
                    failures += 1;
                    eprintln!("line {lineno}: {fields} got {l} {d} want {} {}", e[0], e[1]);
                }
                checked += 1;
            }
            "quantize" => {
                let max: i32 = f[1].parse().unwrap();
                let pixels: Vec<Argb> = f[2].split(',').map(parse_argb).collect();
                let QuantizerResult { color_to_count } = QuantizerCelebi::quantize(&pixels, max);
                let mut got = color_to_count.clone();
                got.sort();
                let want: Vec<(Argb, i64)> = expected
                    .split_whitespace()
                    .map(|p| {
                        let (c, n) = p.split_once(':').unwrap();
                        (parse_argb(c), n.parse().unwrap())
                    })
                    .collect();
                if got != want {
                    failures += 1;
                    for (g, w) in got.iter().zip(want.iter()) {
                        if g != w {
                            eprintln!(
                                "line {lineno}: quantize {max} got {:08x}:{} want {:08x}:{}",
                                g.0, g.1, w.0, w.1
                            );
                        }
                    }
                }
                checked += 1;
            }
            "score" => {
                let pixels: Vec<Argb> = f[2].split(',').map(parse_argb).collect();
                let QuantizerResult { color_to_count } =
                    QuantizerCelebi::quantize(&pixels, f[1].parse().unwrap());
                let got = Score::score(&color_to_count, 4, 0xff4285f4, true);
                let want: Vec<Argb> = expected.split_whitespace().map(parse_argb).collect();
                if got != want {
                    failures += 1;
                    eprintln!("line {lineno}: score got {got:016x?} want {want:016x?}");
                }
                checked += 1;
            }
            k => panic!("unknown vector kind {k} on line {lineno}"),
        }
    }
    assert_eq!(failures, 0, "{failures} vector mismatches out of {checked}");
    eprintln!("checked {checked} vectors");
}
