// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import {
    MaterialStyleMetrics,
    MaterialPalette,
    ListTile,
    SegmentedListItem,
    ListView,
    NavigationBar,
    ShortNavigationBar,
    ShortNavigationBarArrangement,
    NavigationItemIconPosition,
    BottomAppBar,
    NavigationDrawer,
    TextButton,
    ModalNavigationDrawer,
    NavigationRail,
    Horizontal,
    NavigationItem,
    TabBar,
    SecondaryTabBar,
    SearchBar,
    AppBarWithSearch,
    FlexibleBottomAppBar,
    BottomAppBarArrangement,
    MaterialText,
    Vertical,
    ListItem,
    TopAppBar,
    CenterAlignedTopAppBar,
    MediumTopAppBar,
    MediumFlexibleTopAppBar,
    LargeTopAppBar,
    LargeFlexibleTopAppBar,
    CheckBoxTile,
    CheckState,
    AssistChip,
    ElevatedAssistChip,
    FilterChip,
    ElevatedFilterChip,
    InputChip,
    SuggestionChip,
    ElevatedSuggestionChip,
    TimePickerPopup,
    Switch,
    Slider,
    TextField,
    RadioButton,
    RadioButtonTile,
    PopupMenu,
    DropDownMenu,
    MenuItem,
    DatePickerPopup
} from "../../../../src/material.slint";

import { Group } from "../components/group.slint";
import { ComponentCard } from "../components/component_card.slint";
import { MainWindowAdapter } from "../main_window_adapter.slint";
import { FilledIcons, OutlinedIcons } from "../icons.slint";

export global NavigationViewAdapter {
    in_out property <[ListItem]> search_items;
    in property <[bool]> radio_buttons: [ true, false, false ];

    callback search(text: string);
    callback filter_icons(text: string);
    callback radio_button_clicked(index: int);
}

export component NavigationView {
    layout := VerticalLayout {
        alignment: start;
        spacing: MaterialStyleMetrics.spacing_8;
        horizontal-stretch: 1;

        Group {
            title: "Navigation";

            ComponentCard {
                title: "Search";

                Vertical {
                    spacing: MaterialStyleMetrics.spacing_16;
                    alignment: start;

                    SearchBar {
                        leading_icon: OutlinedIcons.search;
                        placeholder_text: "Search color";
                        empty_text: "No search history.";
                        items: NavigationViewAdapter.search_items;

                        edited(text) => {
                            NavigationViewAdapter.search(text);
                        }
                    }

                    AppBarWithSearch {
                        leading-icon: FilledIcons.menu;
                        placeholder-text: "Search color";
                        empty_text: "No search history.";
                        items: NavigationViewAdapter.search_items;

                        edited(text) => {
                            NavigationViewAdapter.search(text);
                        }
                    }

                    MaterialText {
                        text: "Select a color";
                        horizontal_alignment: center;
                    }
                }
            }

            ComponentCard {
                title: "Bottom app bar";

                BottomAppBar {
                    icon_buttons: [
                        {
                            icon: OutlinedIcons.more_vert,
                            enabled: true,

                        },
                        {
                            icon: OutlinedIcons.search,
                            enabled: true,
                            tooltip: "Search"
                        },
                        {
                            icon: OutlinedIcons.favorite,
                            enabled: true,
                            tooltip: "Favorite"
                        },
                    ];
                    fab_icon:  OutlinedIcons.add;
                }
            }

            ComponentCard {
                title: "Flexible bottom app bar";

                FlexibleBottomAppBar {
                    width: 100%;
                    arrangement: BottomAppBarArrangement.space-between;
                    items: [
                        { icon: OutlinedIcons.search, label: "Search", enabled: true },
                        { icon: OutlinedIcons.favorite, label: "Favorite", enabled: true },
                        { icon: OutlinedIcons.add, label: "Add", enabled: true },
                        { icon: OutlinedIcons.more_vert, label: "More", enabled: true },
                    ];
                }
            }

            ComponentCard {
                title: "Navigation bar";

                NavigationBar {
                    items: [
                          {
                             icon: OutlinedIcons.explore,
                             selected_icon: FilledIcons.explore,
                             text: "Explore",
                          },
                          {
                             icon: OutlinedIcons.pets,
                             selected_icon: FilledIcons.pets,
                             text: "Pets",
                          },
                          {
                             icon: OutlinedIcons.account_box,
                             selected_icon: FilledIcons.account_box,
                             text: "Account",
                          },
                    ];
                }
            }

            ComponentCard {
                title: "Short navigation bar";

                Vertical {
                    spacing: MaterialStyleMetrics.spacing_16;

                    ShortNavigationBar {
                        items: [
                            {
                                icon: OutlinedIcons.explore,
                                selected_icon: FilledIcons.explore,
                                text: "Explore",
                            },
                            {
                                icon: OutlinedIcons.pets,
                                selected_icon: FilledIcons.pets,
                                text: "Pets",
                                enabled: false,
                            },
                            {
                                icon: OutlinedIcons.account_box,
                                selected_icon: FilledIcons.account_box,
                                text: "Account",
                                badge: "3",
                                show-badge: true,
                            },
                        ];
                    }

                    ShortNavigationBar {
                        arrangement: ShortNavigationBarArrangement.centered;
                        icon-position: NavigationItemIconPosition.start;
                        items: [
                            {
                                icon: OutlinedIcons.explore,
                                selected_icon: FilledIcons.explore,
                                text: "Explore",
                            },
                            {
                                icon: OutlinedIcons.pets,
                                selected_icon: FilledIcons.pets,
                                text: "Pets",
                            },
                            {
                                icon: OutlinedIcons.account_box,
                                selected_icon: FilledIcons.account_box,
                                text: "Account",
                            },
                            {
                                icon: OutlinedIcons.inbox,
                                selected_icon: FilledIcons.inbox,
                                text: "Inbox",
                            },
                        ];
                    }
                }
            }

            ComponentCard {
                title: "Navigation drawer";

                VerticalLayout {
                    NavigationDrawer {
                        groups: [
                            {
                                title: "Mail",
                                items: [
                                    {
                                        icon: OutlinedIcons.inbox,
                                        selected_icon: FilledIcons.inbox,
                                        text: "Inbox",
                                    },
                                    {
                                        icon: OutlinedIcons.outbox,
                                        selected_icon: FilledIcons.outbox,
                                        text: "Outbox",
                                    },
                                    {
                                        icon: OutlinedIcons.favorite,
                                        selected_icon: FilledIcons.favorite,
                                        text: "Favorites",
                                    },
                                    {
                                        icon: OutlinedIcons.delete,
                                        selected_icon: FilledIcons.delete,
                                        text: "Trash",
                                    }
                                ]
                            },
                            {
                                title: "Labels",
                                items: [
                                    {
                                        icon: OutlinedIcons.bookmark,
                                        selected_icon: FilledIcons.bookmark,
                                        text: "Family",
                                    },
                                    {
                                        icon: OutlinedIcons.bookmark,
                                        selected_icon: FilledIcons.bookmark,
                                        text: "School",
                                    },
                                    {
                                        icon: OutlinedIcons.bookmark,
                                        selected_icon: FilledIcons.bookmark,
                                        text: "Work",
                                    },
                                ]
                            }
                        ];
                    }

                    HorizontalLayout {
                        alignment: center;

                        TextButton {
                            text: "Show modal navigation drawer";

                            clicked => {
                                modal_navigation_drawer.show();
                            }
                        }
                    }
                }
            }

            ComponentCard {
                title: "Navigation rail";

                Horizontal {
                    alignment: center;

                    NavigationRail {
                        height: 500px;
                        fab_icon: FilledIcons.edit;
                        alignment: center;

                        items: [
                            {
                                icon: OutlinedIcons.inbox,
                                selected_icon: FilledIcons.inbox,
                                text: "Inbox",
                            },
                            {
                                icon: OutlinedIcons.outbox,
                                selected_icon: FilledIcons.outbox,
                                text: "Outbox",
                            },
                            {
                                icon: OutlinedIcons.favorite,
                                selected_icon: FilledIcons.favorite,
                                text: "Favorites",
                            },
                            {
                                icon: OutlinedIcons.delete,
                                selected_icon: FilledIcons.delete,
                                text: "Trash",
                            }
                        ];
                    }
                }
            }

            ComponentCard {
                title: "Tabs";

                Horizontal {
                    TabBar {
                        items: [
                         {
                             text: "Video",
                             icon: OutlinedIcons.video_chat,
                         },
                         {
                             text: "Photos",
                             icon: OutlinedIcons.image,
                         },
                            {
                                text: "Audio",
                                icon: OutlinedIcons.music_note,
                            },
                        ];
                    }
                }
            }

            ComponentCard {
                title: "Top app bars";

                Vertical {
                    CenterAlignedTopAppBar {
                        leading-button: { icon: FilledIcons.menu, enabled: true };
                        trailing-buttons: [
                            { icon: FilledIcons.account_circle, enabled: true },
                        ];
                        title: "Product";
                    }

                    TopAppBar {
                        leading-button: { icon: FilledIcons.menu, enabled: true };
                        title: "Small";
                        trailing-buttons: [
                            { icon: FilledIcons.calendar_month, enabled: true },
                            { icon: FilledIcons.more_vert, enabled: true },
                        ];
                    }

                    MediumTopAppBar {
                        leading-button: { icon: FilledIcons.menu, enabled: true };
                        title: "Medium";
                        trailing-buttons: [
                            { icon: FilledIcons.calendar_month, enabled: true },
                            { icon: FilledIcons.more_vert, enabled: true },
                        ];
                    }

                    MediumFlexibleTopAppBar {
                        leading-button: { icon: FilledIcons.menu, enabled: true };
                        title: "Medium flexible";
                        subtitle: "With subtitle";
                        trailing-buttons: [
                            { icon: FilledIcons.calendar_month, enabled: true },
                            { icon: FilledIcons.more_vert, enabled: true },
                        ];
                    }

                    LargeTopAppBar {
                        leading-button: { icon: FilledIcons.menu, enabled: true };
                        title: "Large";
                        trailing-buttons: [
                            { icon: FilledIcons.calendar_month, enabled: true },
                            { icon: FilledIcons.more_vert, enabled: true },
                        ];
                    }

                    LargeFlexibleTopAppBar {
                        leading-button: { icon: FilledIcons.menu, enabled: true };
                        title: "Large flexible";
                        subtitle: "With subtitle";
                        trailing-buttons: [
                            { icon: FilledIcons.calendar_month, enabled: true },
                            { icon: FilledIcons.more_vert, enabled: true },
                        ];
                    }
                }
            }
        }

        Group {
            title: "Selection";

            ComponentCard {
                title: "Checkboxes";

                Vertical {
                    CheckBoxTile {
                        text: "Option 1";
                        tristate: true;
                    }

                    CheckBoxTile {
                        text: "Option 2";
                    }

                    CheckBoxTile {
                        text: "Option 3";
                        tristate: true;
                        has-error: true;
                    }

                    CheckBoxTile {
                        text: "Option 4";
                        enabled: false;
                        check_state: CheckState.checked;
                    }
                }
            }

            ComponentCard {
                title: "RadioButtons";

                Vertical {
                    Horizontal {
                        spacing: 8px;
                        alignment: center;

                        RadioButton {}

                        RadioButton {
                            checked: true;
                        }
                    }

                    RadioButtonTile {
                        text: "Option 1";
                        checked: NavigationViewAdapter.radio_buttons[0];

                        radio_button_clicked => {
                            NavigationViewAdapter.radio_button_clicked(0);
                        }
                    }

                    RadioButtonTile {
                        text: "Option 2";
                        checked: NavigationViewAdapter.radio_buttons[1];

                        radio_button_clicked => {
                            NavigationViewAdapter.radio_button_clicked(1);
                        }
                    }

                    RadioButtonTile {
                        text: "Option 3";
                        checked: NavigationViewAdapter.radio_buttons[2];

                        radio_button_clicked => {
                            NavigationViewAdapter.radio_button_clicked(2);
                        }
                    }

                    RadioButtonTile {
                        text: "Option 4";
                        enabled: false;
                    }
                }
            }

            ComponentCard {
                title: "Chips";

                Vertical {
                    Horizontal {
                        AssistChip {
                            text: "Assist";
                            icon: OutlinedIcons.calendar_month;
                        }

                        fc := FilterChip {
                            checked: true;
                            text: "Filter";
                        }

                        InputChip {
                            text: "Input";
                            avatar_icon: OutlinedIcons.person;
                            trailing_icon: OutlinedIcons.close;
                        }

                        SuggestionChip {
                            text: "Suggestion";
                        }
                    }

                    Horizontal {
                        ElevatedAssistChip {
                            text: "Assist";
                            icon: OutlinedIcons.calendar_month;
                        }

                        ElevatedFilterChip {
                            checked: fc.checked;
                            expressive: true;
                            text: "Filter";
                        }

                        ElevatedSuggestionChip {
                            text: "Suggestion";
                        }
                    }

                    Horizontal {
                        AssistChip {
                            text: "Assist";
                            icon: OutlinedIcons.calendar_month;
                            enabled: false;
                        }

                        FilterChip {
                            checked: fc.checked;
                            text: "Filter";
                            enabled: false;
                        }

                        InputChip {
                            text: "Input";
                            trailing_icon: OutlinedIcons.close;
                            enabled: false;
                        }

                        ElevatedSuggestionChip {
                            text: "Suggestion";
                            enabled: false;
                        }
                    }
                }
            }

            ComponentCard {
                title: "Menus";

                Horizontal {
                    alignment: center;

                    menu_button := TextButton {
                        text: "Show menu";

                        clicked => {
                            menu.show();
                        }
                    }


                    menu := PopupMenu {
                        x: menu_button.x + menu_button.width / 2;
                        y: menu_button.y + menu_button.height / 2;
                        items: [
                            { icon: OutlinedIcons.account_box, text: "Inbox", enabled: true },
                            { icon: OutlinedIcons.outbox, text: "Outbox", enabled: true, trailing_text: "Ctrl C" },
                            { icon: OutlinedIcons.favorite, text: "Favorites", enabled: true },
                            { icon: OutlinedIcons.delete, text: "Trash", enabled: false },
                        ];
                    }
                }
            }

            ComponentCard {
                title: "Time picker";

                Horizontal {
                    alignment: center;

                    TextButton {
                        icon: OutlinedIcons.schedule;
                        text: "Show time picker";

                        clicked => {
                            time_picker.show();
                        }
                    }
                }
            }

            ComponentCard {
                title: "Date picker";

                Horizontal {
                    alignment: center;

                    TextButton {
                        icon: OutlinedIcons.calendar_month;
                        text: "Show date picker";

                        clicked => {
                            date_picker.show();
                        }
                    }
                }
            }

            ComponentCard {
                title: "DropDown menu";

                Horizontal {
                    DropDownMenu {
                        label: "Icon";
                        leading_icon: OutlinedIcons.search;
                        items:
                        [
                            { icon: OutlinedIcons.bookmark, text: "Bookmark", enabled: true },
                            { icon: OutlinedIcons.explore, text: "Explore", enabled: true },
                            { icon: OutlinedIcons.chat_bubble, text: "Chat", enabled: true },
                            { icon: OutlinedIcons.favorite, text: "Favorite", enabled: true },
                        ];
                    }
                }
            }

            ComponentCard {
                title: "Switches";

                Vertical {
                    Horizontal {
                        alignment: space_around;

                        Switch {}

                        Switch {
                            off_icon: FilledIcons.close;
                            on_icon: FilledIcons.check;
                        }
                    }

                    Horizontal {
                        alignment: space_around;

                        Switch {
                            enabled: false;
                        }

                        Switch {
                            enabled: false;
                            on_icon: FilledIcons.check;
                            off_icon: FilledIcons.close;
                        }
                    }
                }
            }

            ComponentCard {
                title: "Sliders";

                Vertical {
                    spacing: MaterialStyleMetrics.size_24;
                    Horizontal {
                        Slider {
                            value: 50;
                        }
                    }

                    Horizontal {
                        Slider {
                            stop_count: 5;
                        }
                    }
                }
            }
        }

        Group {
            title: "Lists";

            ComponentCard {
                title: "Lists";

                Vertical {

                    ListTile {
                        text: "Inbox";
                        supporting_text: "12 new messages";
                        avatar_icon: FilledIcons.inbox;
                        avatar_background: MaterialPalette.primary_container;
                        avatar_foreground: MaterialPalette.on_primary_container;
                        interactive: true;
                        clicked => { self.selected = !self.selected; }
                    }

                    ListTile {
                        text: "Bookmarks";
                        supporting_text: "Messages you marked";
                        avatar_icon: FilledIcons.bookmark;
                        avatar_background: MaterialPalette.secondary_container;
                        avatar_foreground: MaterialPalette.on_secondary_container;
                        selectable: true;
                        trailing_icon: FilledIcons.bookmark;
                    }

                    ListTile {
                        text: "Outbox";
                        avatar_icon: OutlinedIcons.outbox;
                    }

                    ListTile {
                        text: "Trash";
                        supporting_text: "Disabled";
                        avatar_icon: OutlinedIcons.delete;
                        enabled: false;
                    }
                }
            }

            ComponentCard {
                title: "Segmented lists";

                Vertical {

                    SegmentedListItem {
                        text: "Today";
                        supporting_text: "Selected";
                        index: 0;
                        count: 3;
                        selectable: true;
                        selected: true;
                    }

                    SegmentedListItem {
                        text: "This week";
                        index: 1;
                        count: 3;
                        selectable: true;
                    }

                    SegmentedListItem {
                        text: "This month";
                        index: 2;
                        count: 3;
                        interactive: true;
                    }
                }
            }
        }

        Group {
            title: "Text inputs";

            ComponentCard {
                title: "Text fields";

                Vertical {
                    Horizontal {
                        top_tf := TextField {
                            leading_icon: FilledIcons.search;
                            trailing_icon: FilledIcons.close;
                            label: "Filled";
                            placeholder_text: "hint text";
                            supporting_text: "supporting text";

                            leading_icon_clicked => {
                                self.focus();
                            }

                            trailing_icon_clicked => {
                                self.text = "";
                            }
                        }
                    }

                    Horizontal {
                        TextField {
                            text <=> top_tf.text;
                            leading_icon: FilledIcons.search;
                            trailing_icon: FilledIcons.close;
                            label: "Filled";
                            placeholder_text: "hint text";
                            supporting_text: "error text";
                            has_error: true;

                            leading_icon_clicked => {
                                self.focus();
                            }

                            trailing_icon_clicked => {
                                self.text = "";
                            }
                        }

                        TextField {
                            text <=> top_tf.text;
                            leading_icon: FilledIcons.search;
                            trailing_icon: FilledIcons.close;
                            label: "Filled";
                            placeholder_text: "hint text";
                            supporting_text: "supporting text";
                            enabled: false;
                        }
                    }
                }
            }
        }
    }

    modal_navigation_drawer := ModalNavigationDrawer {
        x: -root.absolute_position.x;
        y: -root.absolute_position.y;
        width: MainWindowAdapter.width;
        height: MainWindowAdapter.height;
        position_right: true;
        groups: [
            {
                title: "Mail",
                items: [
                    {
                        icon: OutlinedIcons.inbox,
                        selected_icon: FilledIcons.inbox,
                        text: "Inbox",
                    },
                    {
                        icon: OutlinedIcons.outbox,
                        selected_icon: FilledIcons.outbox,
                        text: "Outbox",
                    },
                    {
                        icon: OutlinedIcons.favorite,
                        selected_icon: FilledIcons.favorite,
                        text: "Favorites",
                    },
                    {
                        icon: OutlinedIcons.delete,
                        selected_icon: FilledIcons.delete,
                        text: "Trash",
                    }
                ]
            },
            {
                title: "Labels",
                items: [
                    {
                        icon: OutlinedIcons.bookmark,
                        selected_icon: FilledIcons.bookmark,
                        text: "Family",
                    },
                    {
                        icon: OutlinedIcons.bookmark,
                        selected_icon: FilledIcons.bookmark,
                        text: "School",
                    },
                    {
                        icon: OutlinedIcons.bookmark,
                        selected_icon: FilledIcons.bookmark,
                        text: "Work",
                    },
                ]
            }
        ];
    }

    time_picker := TimePickerPopup {
        // this is used to place the popup on 0,0 of the window and also to fill the window
        x: -root.absolute_position.x;
        y: -root.absolute_position.y;
        width: MainWindowAdapter.width;
        height: MainWindowAdapter.height;
        title: @tr("Select time");

        ok => {
            time_picker.close();
        }
    }

    date_picker := DatePickerPopup {
        // this is used to place the popup on 0,0 of the window and also to fill the window
        x: -root.absolute_position.x;
        y: -root.absolute_position.y;
        width: MainWindowAdapter.width;
        height: MainWindowAdapter.height;
        title: @tr("Select date");
    }
}
